# name属性用来指定这个工作流的名字
name: check and run

# 这个部分用来指定能够触发工作流执行的事件
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/6 * * * *'
    - cron: '0 17 * * *'


# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build_and_run:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:
      - uses: actions/checkout@v3
      # 步骤，这里只写了一个步骤，目的是输出hello github acition
      - name: Setup railway cli
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          
      #- name: Setup Node.js environment
        #uses: actions/setup-node@v3.1.1
        
      - run: |
          rm README.md
          downloadUrl=`curl https://api.github.com/repos/cloudreve/Cloudreve/releases/latest | grep -o 'https://github.com/cloudreve/Cloudreve/releases/download.*linux_amd64.tar.gz'`
          wget -q -O cr.tar.gz $downloadUrl
          tar -xvf cr.tar.gz
          mv cloudreve cr         
          echo "${{ secrets.CONFIG }}" > config.ini
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up
          
          
